cmd > sqlplus conn as sysdba
SQL > create user mybatis2 identified by mybatis2;
SQL > grant connect, resource to mybatis2;

CREATE TABLE BLOG(
	BLOG_ID NUMBER PRIMARY KEY,
	BLOG_NAME NVARCHAR2(200),
	BLOG_TITLE NVARCHAR2(2000),
	BLOG_AUTHOR_ID NUMBER
);

INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그명1', '블로그제목1', 1);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그명2', '블로그제목2', 1);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그명3', '블로그제목3', 2);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그명4', '블로그제목4', 2);
INSERT INTO BLOG VALUES(SEQ_BLOG.NEXTVAL, '블로그명5', '블로그제목5', 3);
SELECT * FROM BLOG;

CREATE SEQUENCE SEQ_BLOG;

CREATE TABLE AUTHOR (
	AUTHOR_ID NUMBER PRIMARY KEY,
	AUTHOR_NAME NVARCHAR2(200),
	BLOG_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(BLOG_ID)
);

INSERT INTO AUTHOR VALUES(SEQ_AUTHOR.NEXTVAL, '작성자명', 1);
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR.NEXTVAL, '작성자명', 2);
INSERT INTO AUTHOR VALUES(SEQ_AUTHOR.NEXTVAL, '작성자명', 3);
SELECT * FROM AUTHOR;

CREATE SEQUENCE SEQ_AUTHOR;

CREATE TABLE COMM(
	COMM_ID NUMBER PRIMARY KEY,
	COMM_TITLE NVARCHAR2(500),
	COMM_CONTENT NVARCHAR2(2000),
	BLOG_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(BLOG_ID)
);

INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '게시물제목1', '게시물내용1', 1);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '게시물제목2', '게시물내용2', 1);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '게시물제목3', '게시물내용3', 1);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '게시물제목1', '게시물내용1', 2);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '게시물제목2', '게시물내용2', 2);
INSERT INTO COMM VALUES(SEQ_COMM.NEXTVAL, '게시물제목3', '게시물내용3', 2);

SELECT * FROM COMM;

CREATE SEQUENCE SEQ_COMM;

COMMIT;



