CREATE TABLE AUTHOR (
	ID NUMBER PRIMARY KEY,
	USERNAME NVARCHAR2(200),
	PASSWORD VARCHAR2(200),
	EMAIL VARCHAR2(200),
	BIO VARCHAR2(200),
	FAVOURITE_SECTION VARCHAR2(200)
);

CREATE SEQUENCE SEQ_AUTHOR;

CREATE TABLE BLOG(
	ID NUMBER PRIMARY KEY,
	TITLE NVARCHAR2(200),
	BLOG_AUTHOR_ID NUMBER,
	FOREIGN KEY (BLOG_AUTHOR_ID) REFERENCES AUTHOR(ID)
);

CREATE SEQUENCE SEQ_BLOG;

CREATE TABLE POST(
	ID NUMBER PRIMARY KEY,
	CREATED_ON TIMESTAMP,
	SECTION VARCHAR2(200),
	SUBJECT NVARCHAR2(200),
	DRAFT NUMBER,
	BODY NVARCHAR2(2000),
	BLOG_ID NUMBER,
	POST_AUTHOR_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(ID),
	FOREIGN KEY (POST_AUTHOR_ID) REFERENCES AUTHOR(ID)
);

CREATE SEQUENCE SEQ_POST;

CREATE TABLE TAG(
	ID NUMBER PRIMARY KEY,
	NAME NVARCHAR2(200),
	POST_ID NUMBER,
	FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE SEQUENCE SEQ_TAG;

CREATE TABLE CMT(
	ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(200),
	CMT NVARCHAR2(2000),
	POST_ID NUMBER,
	FOREIGN KEY (POST_ID) REFERENCES POST(ID)
);

CREATE SEQUENCE SEQ_CMT;

INSERT INTO AUTHOR
VALUES(SEQ_AUTHOR.NEXTVAL, 'USERNAME', 'PASSWORD', 'EMAIL', 'BIO', 'FAVOURITE_SECTION');

SELECT * FROM AUTHOR;

INSERT INTO BLOG
VALUES(SEQ_BLOG.NEXTVAL, 'TITLE', 4);

SELECT * FROM BLOG;

INSERT INTO POST
VALUES(SEQ_POST.NEXTVAL, SYSDATE, 'SECTION', 'SUBJECT', 1, 'BODY', 2, 4);

SELECT * FROM POST;

INSERT INTO TAG
VALUES(SEQ_TAG.NEXTVAL, 'NAME', 6);

SELECT * FROM TAG;

INSERT INTO CMT VALUES(SEQ_CMT.NEXTVAL, 'NAME', 'COMMENT', 7);

SELECT * FROM CMT;

COMMIT;
